### ISSUE TITLE
Polyfill for IE 10/11 classList.remove and classList.add supports only one argument at a time(for elements like body, div ...).

### ISSUE THREAD

**Issue by andriidudar** [yola/classlist-polyfill-old#13]
It was broken by commit 2f3db7014660b12321b6ac6368c9577496327d3d.

``` js
// Full polyfill for browsers with no classList support
 -  if (!("classList" in document.createElement("_"))) {
 +  // Including IE < Edge missing SVGElement.classList
 +  if (!("classList" in document.createElement("_"))
 +    || document.createElementNS && !("classList" in document.createElementNS("http://www.w3.org/2000/svg","g"))) {
```

After this modification we extend object prototype with new functionality we don't modify native IE implementation for simple elements(Body, Div, Span).

**Comment by snitch** [comment]
@DevShep: This issue is now a priority.

**Comment by LionOps** [comment]
Hi @andriidudar. This polyfill is a copy of https://github.com/eligrey/classList.js and I don't think we should be addressing the problem you discovered in this repo.

It looks like https://github.com/eligrey/classList.js/issues/44 is what you've described. I encourage you to post there. Once that issue is resolved, we'll make the changes here.

Thanks.
